import React from 'react';
import { useLocation, useParams, Link } from 'react-router-dom';
import { GemmaBadge } from '../components/GemmaBadge';
import { RoadmapTimeline } from '../components/RoadmapTimeline';
import { ChevronLeft, Compass } from 'lucide-react';
import type { LearningRoadmap } from '../types';

export const RoadmapPage: React.FC = () => {
  const { reportId } = useParams<{ reportId: string }>();
  const location = useLocation();

  // Roadmap is always passed via navigation state from OpportunityDetailPage
  const roadmap = location.state?.roadmap as LearningRoadmap | undefined;

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-[#334155] pb-4">
        <div className="space-y-1">
          <Link
            to="/opportunities"
            className="flex items-center gap-1 text-xs font-semibold text-[#94A3B8] hover:text-white transition-colors"
          >
            <ChevronLeft className="w-4 h-4" />
            Back to Opportunities
          </Link>
          {roadmap && (
            <h1 className="text-xl md:text-2xl font-extrabold text-white">
              Learning Roadmap — <span className="text-[#818CF8]">{roadmap.roleTitle}</span>
            </h1>
          )}
        </div>
        <GemmaBadge />
      </div>

      {roadmap ? (
        <div className="space-y-6">
          {/* Stats bar */}
          <div className="grid grid-cols-3 gap-4">
            <div className="bg-[#1E293B] border border-[#334155] rounded-xl p-4 text-center">
              <div className="text-2xl font-extrabold text-[#818CF8]">{roadmap.steps?.length || 0}</div>
              <div className="text-xs text-[#94A3B8] mt-1">Learning Modules</div>
            </div>
            <div className="bg-[#1E293B] border border-[#334155] rounded-xl p-4 text-center">
              <div className="text-2xl font-extrabold text-[#22C55E]">
                {roadmap.steps?.reduce((acc, s) => acc + (s.estimatedHours || 0), 0) || 0}h
              </div>
              <div className="text-xs text-[#94A3B8] mt-1">Estimated Hours</div>
            </div>
            <div className="bg-[#1E293B] border border-[#334155] rounded-xl p-4 text-center">
              <div className="text-2xl font-extrabold text-[#F59E0B]">{roadmap.projects?.length || 0}</div>
              <div className="text-xs text-[#94A3B8] mt-1">Practice Projects</div>
            </div>
          </div>

          {/* Timeline */}
          <div className="bg-[#1E293B] border border-[#334155] rounded-xl p-6 shadow-xl">
            <RoadmapTimeline roadmap={roadmap} />
          </div>

          {/* Projects */}
          {roadmap.projects && roadmap.projects.length > 0 && (
            <div className="space-y-3">
              <h2 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
                <span className="w-2 h-2 bg-[#F59E0B] rounded-full" />
                Practice Projects
              </h2>
              {roadmap.projects.map((project, idx) => (
                <div key={idx} className="bg-[#1E293B] border border-[#334155] rounded-xl p-5 space-y-3">
                  <h3 className="font-bold text-white text-sm">{project.title}</h3>
                  <p className="text-xs text-[#94A3B8] leading-relaxed">{project.description}</p>
                  <div className="flex flex-wrap gap-1.5">
                    {project.skillsExercised?.map((skill: string) => (
                      <span key={skill} className="text-[10px] bg-[#F59E0B]/10 border border-[#F59E0B]/30 text-[#FCD34D] px-2 py-0.5 rounded font-semibold">
                        {skill}
                      </span>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          )}

          <p className="text-center text-[10px] text-[#475569]">
            This roadmap was generated by <span className="text-[#818CF8] font-semibold">Gemma 4 E2B</span> running locally on your machine
          </p>
        </div>
      ) : (
        <div className="flex flex-col items-center justify-center py-24 bg-[#1E293B]/20 border border-[#334155] border-dashed rounded-xl space-y-4">
          <Compass className="w-14 h-14 text-[#64748B]" />
          <div className="text-center space-y-2">
            <h3 className="font-bold text-white text-base">No Learning Roadmap Active</h3>
            <p className="text-xs text-[#94A3B8] max-w-xs">
              To generate a personalized study plan, open an Opportunity, run the Skill Gap Analysis, then click "Generate Learning Roadmap".
            </p>
          </div>
          <Link
            to="/opportunities"
            className="mt-2 bg-[#4F46E5] hover:bg-[#4F46E5]/90 text-white font-bold px-5 py-2 rounded-lg text-xs transition-colors"
          >
            Browse Opportunities
          </Link>
        </div>
      )}
    </div>
  );
};
export default RoadmapPage;
